######### Epidemiologic Methods 3 ##############################################

# Lab 2: Risk Factors for Death after End-Stage Renal Disease in Adults 
#     with HIV in North America

######### Load Packages ########################################################

# Load Packages
# Note: Use install.packages("[name_of_package]") if a package is not installed.
library(tidyverse)
library(haven)
library(lattice)

######### Import Stata Data File ###############################################

# Open Lab 2 dataset
# Note: The haven package contains several functions that can be used to read
# data generated by other statistical packages, including Stata and SAS.
dataset <- read_dta("2020_Epi753_Lab2.dta")

######### At-Home Question 1 ###################################################

# Look for missing values of the risk factor variables
sum(is.na(dataset$age))
sum(is.na(dataset$sex))
sum(is.na(dataset$black))
sum(is.na(dataset$idu))
sum(is.na(dataset$hcv))
sum(is.na(dataset$hbv))
sum(is.na(dataset$smoking))
sum(is.na(dataset$htn))
sum(is.na(dataset$diabetes))
sum(is.na(dataset$cd4))
sum(is.na(dataset$ud_vl200))
sum(is.na(dataset$art))

# Note: You can use sapply() to loop over all of the variables in a data frame
# and apply a function such as the one above to each of them:
# sapply(dataset, function(x) sum(is.na(x)))

######### At-Home Question 2 ###################################################

# Look at the distribution of CD4 at ESRD by death status
boxplot(cd4 ~ death, data = dataset)

dataset %>% 
    group_by(death) %>%
    summarize(n = n(),
        min = min(cd4),
        median = median(cd4),
        max = max(cd4),
        mean = mean(cd4),
        sd = sd(cd4))

# Note: You can specify plot and axis labels for boxplot():
# boxplot(cd4 ~ death, data = dataset,
#    main = "CD4+ T-Lymphocyte Counts by Vital Status",
#    ylab = expression("CD4+ T-Lymphocyte Count " * (cells/m^3)), 
#    xlab = "Vital Status at End of Follow-up", 
#    names = c("Alive", "Dead"))

######### At-Home Question 5 ###################################################

# Modify the form of the age variable (by making ordinal categories)
dataset <- dataset %>% mutate(age_cat = 
    ifelse(age >= 0  & age < 30, 1,
    ifelse(age >= 30 & age < 40, 2,
    ifelse(age >= 40 & age < 50, 3,
    ifelse(age >= 50 & age < 60, 4,
    ifelse(age >= 60 & age < 70, 5,
    ifelse(age >= 70 & age != ., 6, NA)))))))

# Note: In R, we can use factor() to label categorical values.
dataset$age_cat <- factor(dataset$age_cat, 
    levels = c(1:6), 
    labels = c("<30", 
        "30-39", 
        "40-49", 
        "50-59", 
        "60-69", 
        ">=70"))

addmargins(table(dataset$age_cat))

######### In-Class Question 4 ##################################################

# Number of participants who die after ESRD diagnosis
addmargins(table(dataset$death))

######### In-Class Question 5 ##################################################

# Modify the forms of the risk factor variables
histogram(dataset$age)
dataset <- dataset %>% mutate(age10 = age / 10)

histogram(dataset$cd4)
dataset <- dataset %>% mutate(cd4gte350 = ifelse(cd4 >= 350, 1, 0))

######### In-Class Question 6 ##################################################

# Statistics for a table investigating the correlation between the risk factors 
# and death

# Means
t.test(age ~ death, data = dataset)

# Proportions
dataset %>%
    group_by(death) %>%
    summarize(sex = mean(sex), 
        black = mean(black),
        idu = mean(idu),
        hcv = mean(hcv),
        hbv = mean(hbv),
        smoking = mean(smoking, na.rm = TRUE),
        htn = mean(htn),
        diabetes = mean(diabetes),
        cd4gte350 = mean(cd4gte350),
        ud_vl200 = mean(ud_vl200),
        art = mean(art))

# Table of Counts
addmargins(table(dataset$death, dataset$sex))

# Table of Column Proportions
prop.table(table(dataset$death, dataset$sex), margin = 2)

# Fisher's Exact Test
fisher.test(table(dataset$death, dataset$sex))

######### In-Class Question 7 ##################################################

# Note: In R, if we call glm() but do nothing else, a limited amount of
# information is returned to the console.
glm(death ~ age10, data = dataset, family = binomial(link = log))

# Note: We can enclose glm() within summary() so that more information is
# returned to the console.
summary(glm(death ~ age10, data = dataset, family = binomial(link = log)))

# Note: We can use coef() enclosed within exp() to return the exponentiated 
# coefficients, i.e., the relative risks.
exp(coef(glm(death ~ age10,     data = dataset, family = binomial(link = log))))
exp(coef(glm(death ~ sex,       data = dataset, family = binomial(link = log))))
exp(coef(glm(death ~ black,     data = dataset, family = binomial(link = log))))
exp(coef(glm(death ~ idu,       data = dataset, family = binomial(link = log))))
exp(coef(glm(death ~ hcv,       data = dataset, family = binomial(link = log))))
exp(coef(glm(death ~ hbv,       data = dataset, family = binomial(link = log))))
exp(coef(glm(death ~ smoking,   data = dataset, family = binomial(link = log))))
exp(coef(glm(death ~ htn,       data = dataset, family = binomial(link = log))))
exp(coef(glm(death ~ diabetes,  data = dataset, family = binomial(link = log))))
exp(coef(glm(death ~ cd4gte350, data = dataset, family = binomial(link = log))))
exp(coef(glm(death ~ ud_vl200,  data = dataset, family = binomial(link = log))))
exp(coef(glm(death ~ art,       data = dataset, family = binomial(link = log))))

######### In-Class Question 8 ##################################################

# Exclude Observations with Missing Data
dataset2 <- dataset[complete.cases(dataset),]

# Model 1: Multivariable Log Bionomial Regression Model
glm(death ~ age10 + black + idu + hbv + htn + diabetes + smoking + cd4gte350 + 
        ud_vl200, data = dataset2, family = binomial(link = "log"))

######### In-Class Question 9 ##################################################

# Model 2: Backwards Step-wise Regression for a Multivariable Logistic 
#     Regression Model

# First, we fit a model with all covariates (the starting model)
start <- glm(death ~ age10 + black + idu + hbv + htn + diabetes + cd4gte350 + 
    ud_vl200, data = dataset, family = binomial(link = "log"))

# Second, we fit a model with just an intercept (toward which we will move)
end <- glm(death ~ 1, data = dataset, family = binomial(link = "log"))

# Second, we call step() and specify direction = "backward." The stepwise
# regression begins with all_covarites and moves towards intercept-only.
step(start, direction = "backward", scope = formula(end))

######### In-Class Question 10 ##################################################

# Model 3: Logistic Regression Model
glm(death ~ age10 + black + idu + hbv + smoking + htn + diabetes + cd4gte350 + 
        ud_vl200, data = dataset, family = binomial(link = "logit"))

######### In-Class Question 11 ##################################################

# Model 1 + sex (demonstrating a model that will not converge)
glm(death ~ age10 + black + idu + hbv + htn + diabetes + cd4gte350 + 
    ud_vl200, data = dataset, family = binomial(link = "log"))

# Model 4 = Model + sex Using a Multivariable Poisson Regression Model
# Note: I need to add robust variance estimation.
glm(death ~ age10 + black + idu + hbv + smoking + htn + diabetes + cd4gte350 + 
    ud_vl200, data = dataset, family = poisson(link = "log"))
